// ==UserScript==
// @name         4chan-neXT
// @version      1.0.7
// @minGMVer     1.14
// @minFFVer     78
// @namespace    4chan-neXT
// @description  4chan-neXT is a script that adds various features to anonymous imageboards.
// @license      MIT; https://github.com/cercos/4chan-next/blob/project-neXT/LICENSE
// @include      https://boards.4chan.org/*
// @include      https://sys.4chan.org/*
// @include      https://4chan.org/*
// @include      https://www.4chan.org/*
// @include      https://i.4cdn.org/*
// @include      https://is.4chan.org/*
// @include      https://is2.4chan.org/*
// @include      https://erischan.org/*
// @include      https://www.erischan.org/*
// @include      https://fufufu.moe/*
// @include      https://kakashinenpo.com/*
// @include      https://www.kakashinenpo.com/*
// @include      https://kissu.moe/*
// @include      https://www.kissu.moe/*
// @include      https://original.kissu.moe/*
// @include      https://lainchan.org/*
// @include      https://www.lainchan.org/*
// @include      https://merorin.com/*
// @include      https://ota-ch.com/*
// @include      https://www.ota-ch.com/*
// @include      https://ponyville.us/*
// @include      https://www.ponyville.us/*
// @include      https://smuglo.li/*
// @include      https://notso.smuglo.li/*
// @include      https://smugloli.net/*
// @include      https://smug.nepu.moe/*
// @include      https://sportschan.org/*
// @include      https://www.sportschan.org/*
// @include      https://sushigirl.us/*
// @include      https://www.sushigirl.us/*
// @include      https://tvch.moe/*
// @match        https://boards.4chan.org/*
// @match        https://sys.4chan.org/*
// @match        https://4chan.org/*
// @match        https://www.4chan.org/*
// @match        https://i.4cdn.org/*
// @match        https://is.4chan.org/*
// @match        https://is2.4chan.org/*
// @match        https://*.4chan.org/*
// @match        https://*.4cdn.org/*
// @match        https://erischan.org/*
// @match        https://www.erischan.org/*
// @match        https://fufufu.moe/*
// @match        https://kakashinenpo.com/*
// @match        https://www.kakashinenpo.com/*
// @match        https://kissu.moe/*
// @match        https://www.kissu.moe/*
// @match        https://original.kissu.moe/*
// @match        https://lainchan.org/*
// @match        https://www.lainchan.org/*
// @match        https://merorin.com/*
// @match        https://ota-ch.com/*
// @match        https://www.ota-ch.com/*
// @match        https://ponyville.us/*
// @match        https://www.ponyville.us/*
// @match        https://smuglo.li/*
// @match        https://notso.smuglo.li/*
// @match        https://smugloli.net/*
// @match        https://smug.nepu.moe/*
// @match        https://sportschan.org/*
// @match        https://www.sportschan.org/*
// @match        https://sushigirl.us/*
// @match        https://www.sushigirl.us/*
// @match        https://tvch.moe/*
// @exclude      https://www.4chan.org/advertise
// @exclude      https://www.4chan.org/advertise?*
// @exclude      https://www.4chan.org/donate
// @exclude      https://www.4chan.org/donate?*
// @connect      4chan.org
// @connect      4channel.org
// @connect      4cdn.org
// @connect      4chenz.github.io
// @connect      archive.4plebs.org
// @connect      warosu.org
// @connect      desuarchive.org
// @connect      boards.fireden.net
// @connect      arch.b4k.dev
// @connect      archived.moe
// @connect      thebarchive.com
// @connect      archiveofsins.com
// @connect      archive.palanq.win
// @connect      eientei.xyz
// @connect      api.clyp.it
// @connect      api.dailymotion.com
// @connect      api.github.com
// @connect      soundcloud.com
// @connect      api.streamable.com
// @connect      vimeo.com
// @connect      www.youtube.com
// @connect      *
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_listValues
// @grant        GM_addValueChangeListener
// @grant        GM_openInTab
// @grant        GM_xmlhttpRequest
// @grant        GM_addElement
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.deleteValue
// @grant        GM.listValues
// @grant        GM.openInTab
// @grant        GM.xmlHttpRequest
// @run-at       document-start
// @updateURL    https://github.com/cercos/4chan-next/releases/latest/download/4chan-neXT.meta.js
// @downloadURL  https://github.com/cercos/4chan-next/releases/latest/download/4chan-neXT.user.js
// @icon         data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAACVBMVEUAAGcAAABmzDNZt9VtAAAAAXRSTlMAQObYZgAAAF5JREFUeNrtkTESABAQxPD/R6tsE2dUGYUtFJvLDKf93KevHJAjpBorAQWSBIKqFASC4G0pCAkm4GfaEvgYXl0T6HBaE97f0vmnfYHbZOMLZCx9ISdKWwjOWZSC8GYm4SUGwfYgqI4AAAAASUVORK5CYII=
// @license      MIT
// ==/UserScript==
